services:
  # 1. Backend Web Service (Docker container)
  - type: web
    name: rag-backend-service
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: singapore
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false

# 2. Frontend Static Site Service
staticSites:
  - name: rag-frontend-service
    buildCommand: ""
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html