services:
  # 1. Backend Web Service (FastAPI Docker Container)
  - type: web
    name: rag-backend-service
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: singapore
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false

  # 2. Frontend Static Site (HTML/JS)
  - type: web
    name: rag-frontend-service
    runtime: static
    buildCommand: ""
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html